version: "3"

services:
  traefik:
    image: traefik:2.2
    restart: always
    command:
      --api.insecure=true
      --providers.docker
      --entryPoints.web.address=:80
      # --log.level=DEBUG
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      # - "443:443"
       # The Web UI enabled by --api.insecure=true
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  site:
    image: registry.jvansan.duckdns.org/atlas_curator:3.3.2
    restart: always
    env_file:
      - ./flask.env
    labels:
      - traefik.http.routers.curator.rule=PathPrefix(`/`)
    volumes:
      - ./app:/curator/app
      - ./migrations:/curator/migrations
      - ./tests:/curator/tests
    command: [/opt/conda/bin/conda, run, --no-capture-output, -n, curator, flask, run, --host=0.0.0.0]


  celery:
    image: registry.jvansan.duckdns.org/atlas_curator:3.3.2
    restart: always
    env_file:
      - ./flask.env
    command: [/opt/conda/bin/conda, run, --no-capture-output, -n, curator, celery, -A, celery_worker.celery, worker, --loglevel=INFO, --uid=uwsgi]

  redis:
    image: redis
    restart: always
    volumes:
      - $HOME/docker_volumes/redis:/data
    command: ["redis-server", "--appendonly", "yes"]

  mysql:
    image: mysql:5.7
    restart: always
    env_file: 
      - mysql.env
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - $HOME/docker_volumes/mysql:/var/lib/mysql
    ports:
      # The HTTP port
      - "3306:3306"
