version: "3"

services:
  traefik:
    image: traefik:2.2
    # Enables the web UI and tells Traefik to listen to docker
    # Enables self-signed certificates for development
    command:
      --providers.docker
      --api.insecure=true
      --entrypoints.web.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI enabled by --api.insecure=true
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/docker_volumes/acme/:/acme/

  site:
    image: registry.jvansan.duckdns.org/atlas_curator:3.2.2
    restart: always
    env_file:
      - ./flask.env
    labels:
      - traefik.http.services.curator.loadbalancer.server.port=5000
      - traefik.http.routers.curator.entrypoints=web
      - traefik.http.routers.curator.rule=PathPrefix(`/`)
      - "traefik.http.middlewares.curator-gzip.compress=true"
      - "traefik.http.routers.curator.middlewares=curator-gzip@docker"


  celery:
    image: registry.jvansan.duckdns.org/atlas_curator:3.2.2
    restart: always
    env_file:
      - ./flask.env
    command: [/opt/conda/bin/conda, run, --no-capture-output, -n, curator, celery, -A, celery_worker.celery, worker, --loglevel=INFO, --uid=uwsgi]

  redis:
    image: redis
    restart: always
    volumes:
      - $HOME/docker_volumes/redis:/data
    command: ["redis-server", "--appendonly", "yes"]

  mysql:
    image: mysql:5.7
    restart: always
    env_file: 
      - mysql.env
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - $HOME/docker_volumes/mysql:/var/lib/mysql
