version: "3"

services:
  traefik:
    image: traefik:2.2
    restart: always
    command:
      --api.insecure=true
      --providers.docker
      --entryPoints.web.address=:80
      # --log.level=DEBUG
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      # - "443:443"
      # The Web UI enabled by --api.insecure=true
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  site:
    image: ghcr.io/npatlas/atlas_curator:3.3.12
    restart: always
    env_file:
      - ./flask.env
    labels:
      - traefik.http.routers.curator.rule=PathPrefix(`/`)
    volumes:
      - ./app:/home/flask/app/app
      - ./migrations:/home/flask/app/migrations
      - ./tests:/home/flask/app/tests
    depends_on:
      - mysql
      - redis
    command:
      [
        flask,
        run,
        --host=0.0.0.0,
      ]

  celery:
    image: ghcr.io/npatlas/atlas_curator:3.3.12
    restart: always
    env_file:
      - ./flask.env
    volumes:
      - ./app:/home/flask/app/app/
    depends_on:
      - mysql
      - redis
    command:
      [
        celery,
        -A,
        celery_worker.celery,
        worker,
        --loglevel=INFO,
      ]

  # Dont expose ports in prod - no auth 
  redis:
    image: redis
    restart: always
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]

  mysql:
    image: mariadb:10-jammy
    restart: always
    env_file:
      - mysql.env
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  # These are useful for a sandbox version with NP ATLAS DEV API
  api:
    image: ghcr.io/npatlas/npatlas_api:0.1.4
    restart: always
    env_file:
      - api.env
    labels:
      - traefik.http.routers.atlas-api.rule=PathPrefix(`/api/v1`)
    command:
      - "/start-reload.sh"
    depends_on:
      - atlasdb
      - redis

  atlasdb:
    image: mcs07/postgres-rdkit
    restart: always
    env_file:
      - psql.env
    volumes:
      - psqldata:/var/lib/postgresql/data
    ports:
      - 5432:5432

# These external volumes are for persistent data
volumes:
  psqldata:
    external: true
  mysqldata:
    external: true
  redisdata:
    external: true
